version: '3.8'
services:
  app:
    build: ./app
    image: prometheus-java-demo-app:latest
    container_name: prometheus-java-demo-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-java-demo-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    container_name: prometheus-java-demo-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
